### ISSUE TITLE
What is 'gridded geodetic data'

### ISSUE THREAD

**Issue by RogerLott** [opengeospatial/CRS-Gridded-Geodetic-data-eXchange-Format#3]
A) Geodetic data is ...
1)	positioning by coordinates
2)	spatially 1D, 2D or 3D
3)	dynamic (kinematic) or static
4)	produced by 'geodetic institutions'
5)	consumed by GIS
6)	used in coordinate operations

B) Geodetic data is not ...
1)	positioning by geographic identifiers (post codes, etc)
2)	support for non-geodetic activities, even those with a spatial component

In the context of geodetic data,
C) a grid is ...
1)	spatially 2D or 3D
2)	regularly spaced in a defined coordinate space ...
3)	... with orthogonal axes 
4)	generally (but not necessarily) a continuous coverage
5)	may include null values
6)	may have areas with different density coverage

D) a grid is not ...
1)	Irregularly spaced (TIN)
2)	Sparsely sampled

**Comment by rouault** [comment]
>     1. spatially 2D or 3D

What could be the use cases for 3D grids in the context of GGXF ? Would that 3rd dimension only be spatial (along some vertical direction ?) or potentially also temporal ? Do we expect the number of samples along that 3rd dimension to be relatively small compared to the dimension of the horizontal part, or potentially large ?
I'm asking this since some 2D grid formats like GeoTIFF can be used to emulate 3D grids by linking together several 2D grids if the amount remains small (let's say < 100), but that wouldn't scale very well beyond that.

**Comment by RogerLott** [comment]
Possibly (repeat, possibly) a deformaton model grid. We need to see what that project comes up with.

**Comment by strobpr** [comment]
When reading through this I miss one fundamental clarification from the outset, which is that the GGXF grid structure is applicable exclusively to data (or samples/observations/measurements/parameter/values) which represent an area which is (negligibly) small with respect to the area between adjacent samples. Then and only then the ‘domain of validity’ can be defined as in #6 .

In GeoTIFF the class GTRasterTypeGeoKey deals with this fundamental difference. What I really never understood is why the use of ‘PixelIsPoint’ (this case) vs. ‘PixelIsArea’ has not been made compulsory and aligned with the type of values stored. It describes one, if not the most, fundamental difference gridded data may yield. GGXF is thereby exclusively ‘PixelIsPoint’ and can’t be used e.g. for coverages like EO imagery, that should be clearly outlined here when mentioning 'coverages'.

**Comment by ccrook** [comment]
This discussion is now superseded by the specification.  Closing as no longer current.
