### ISSUE TITLE
Amendment to the netCDF layout proposal

### ISSUE THREAD

**Issue by desruisseaux** [opengeospatial/CRS-Gridded-Geodetic-data-eXchange-Format#36]
# Text proposal

Following paragraphs are copied from §8.3.4 (Representation of grid data) in draft 0.92 (2022-07-08). The texts in _italic_ are proposed additions and the texts in ~strikethrough~ are proposed removals. Everything else are unmodified texts.

> Each GGXF grid contains an attribute "data", which is multi-dimensional array containing the data of the parameters in the grid. This is a single array in the GGXF logical model.
>
> In the NetCDF implementation this will be represented by one or more NetCDF variables. GGXF parameters which correspond to axes of the source or target coordinate systems are combined into a single NetCDF variable representing a vector in that coordinate systems. For example GGXF parameters displacementNorth, displacementEast, displacementUp are combined into a single NetCDF variable called displacement. At each grid node this has axes (east, north, and up).
>
> ~The names of the axes are directions as defined for the CoordinateSystems::AxisDirection class in the OGC Abstract Specification Topic 2, "Referencing by Coordinates". These should correspond to the axis directions defined for the source and target coordinate systems except for projection coordinate systems with an origin at the north or south pole. In this case the CRS definition will have axes ("south","south") or ("north","north"), but the GGXF axes will be defined as ("north","east") corresponding to the northing or easting axes.~ _The axes at each grid node should correspond to the axes defined for the source or target coordinate systems. The mapping is defined in two ways: by axis indices in the source or target coordinate system, and by GGXF parameter names. Those two ways are redundant, but useful in different scenarios and not always easy to derive from each other._

[Off] Note about the two ways being redundant: this is similar to the geographic bounding box being redundant with the affine transform + grid size. The former could be derived from the latter, but it is difficult enough (especially for software which do not have a map projection library) for making worth to accept some redundancy.

> The axes in the variable may be a subset of the coordinate axes. For example the vector may represent horizontal deformation applying in a 3 dimensional source and target CRS. In this case the vector will have axes ("north","east") but the source and target CRS will have axis directions ("north","east","up"). _This is described by axis indices {0, 1}._
>
> The vector axes may be in a different order to the source or target CRS, _for example with axis indices {1,0}._
>
> The size of the NetCDF variable is defined by NetCDF dimension attributes. Each variable will have a dimension for each interpolation coordinate axis. These are called iNodeCount, jNodeCount, kNodeCount (for 3d interpolation grids) and are defined in the NetCDF group representing the grid. If the GGXF group includes vector variables, then all the vector variables must have the same axes. The NetCDF group representing the GGXF group header will contain a dimension called axes specifying the number of axes in each vector variable, and ~an attribute called axes containing a one dimensional array of the names of the axes.~ two attributes:
>
> * _one called axisIndices containing a one dimensional array of the zero-based indices of the axes in the coordinate system._
> * _one called axisParameters containing a one dimensional array of the names of the GGXF parameters._

# Example
Following is adapted from the deformation model example in [wiki](https://github.com/opengeospatial/CRS-Gridded-Geodetic-data-eXchange-Format/wiki/NetcdfExamplesLayout2). It does not repeat all attributes in order to focus more on the axes:

```
netcdf DeformationModel {

    // global attributes:
    :conventions = "GGXF-1.0"
    :title = "New Zealand Deformation Model"

    group: nz_linz_nzgd2000-ndm-grid02 {
        :title = "(…) model derived from NUVEL-1A rotation rates"
        :affine_coeffs = [-25.0, 0.0, -0.5, 158.0, 0.5, 0.0]
        :axis_indices = {1, 0}
        :axis_parameters = {"displacementEast", "displacementNorth"}
    
        dimensions:
            axis = 2
            i = 73
            j = 67

        variables:
            float displacement(j, i, axis)
}
```

**Comment by desruisseaux** [comment]
I think that Chris has an alternative proposal where `axis_indices` and `axis_parameters` would be defined in the file header. It would be the same example as above, with only  `:axis_indices` and `:axis_parameters` moved a few lines up. In above proposal I keep those two attributes in the same block that the one that define the `axis` dimension, because they are closely related.

**Comment by ccrook** [comment]
Thanks Martin. I haven't fully worked through putting the information the header.  The main difference to this is that the axis indices and variable names are defined in the file header.  I'll make a complete description for comparison that but probably not till Monday NZ.  

Two cases that come to mind that would be good to include in this would be adding uncertainty to this example where uncertainty similar (ie one for each parameter) and different (displacements are east, north, up, uncertainty is horizontal, up)

**Comment by ccrook** [comment]
@RogerLott @desruisseaux 

Below is the relevant CDL for the approach I was suggesting.  This adds two potential attributes to each parameter definition:

* crs_axis specifying which source CRS axis the parameter refers to if there is a specific axis.  _(In the example below displacementHorizontalUncertainty does not apply to a specific axis.  displacementUpUncertainty does though I haven't specified it.  Could there be a case where it needs to refer to a targetCRS axis that is not also a sourceCRS axis.  Should both be specified if applicable)_
* vector_name specifies the name of the NetCDF variable that will hold the parameter.  

Note 0: This proposal allows GGXF reading software to be independent of content type which is a principle I would like to follow. For example the software does not need to know or infer that the variable name of a displacementEast parameter will be displacement.  Instead it reads this information from the GGXF file.  This allows custom or new GGXF types without modifying the GGXF software. 

Note 1: The NetCDF parameter name is defined by a "vector_name" attribute of each parameter.   If the parameter does not include this attribute is assumed to be a scalar attribute, the name of the NetCDF variable will be the same as the parameter name and the dimensions of the variable will be (j_node_count, i_node_count).

Note 2: The variables in each ggxfGridGroup and the order of parameters in them is defined by the group_parameters attribute in the ggxfGroup as in the current proposal.  

Note 3: It may worth including the "crsAxis" and "vectorName" attributes in the GGXF and YAML specification rather than just as a NetCDF implementation attribute.  This would provide a stronger alignment of the YAML and NetCDF implementations.  It would also allow mapping from YAML to NetCDF without content type domain knowledge.  Having vectorName as a GGXF parameter attribute would also support software requesting data by vector name rather than by scalar parameter name (eg I want the parameters for vectorName=displacement).

Note 4: This proposal does not require any convention in terms of the vectorName of a parameter.  For example a GGXF file could contain an attribute "displacementEast" with vector name "banana".  It would be readable by GGXF software, and it could use it to return the name of the displacementEast parameter.  I don't think this is particularly useful (!).  The GGXF specification should specify the vectorName(s) for each parameter of the content types it defines.

Note 5: (warning: unpalatable note)  Thinking about Note 0 and Note 4, I wonder if the specification would be clearer if it made a clear distinction between format specification and content type.  That is, the specification defines the format in a content agnostic way.  This would mainly (exclusively ?) impact on the tables in Annex C.  Content domain keywords would not be included in the GGXF keyword list in table C1 or elsewhere in Annex C.  The content domain keywords are attribute values, not attribute names (apart from potentially variable names in NetCDF).  They are a controlled vocabulary, but they belong to the content domain of a specific GGXF content type, not to the GGXF domain itself.  Content type specifications could be inserted as Annex D with a sub-section for each content type defining (at least) the parameter names for each content type and domain specific attributes and code lists (eg tidal surfaces).  This would make it very clear how a new content type would be specified.  

The main component of each content type specification would 
* the content type keyword defining the type
* the list of mandatory and optional parameters for each content type
* for each parameter define a) does it require a crs_axis value, b) is a vector name defined for the attribute,...
* domain specific file or group attributes and code lists (eg tidal surface, time functions?)

Note 6: (question).  Are time functions GGXF attributes, or content type attributes?  There are reasons for choosing either.  I think this mainly depends whether we think that time varying parameters is something that will be useful for other content types.  My inclination is that it is a content domain attribute as the definition and handling of time functions is domain specific.   If a content type other than deformation model wants to define time functions it will use its own implementation and attributes (though it may choose to replicate the deformation content type implementation). This means that the library interface to GGXF doesn't include handling a potential time parameter, which is simpler for most content types (a desire for GGXF).  It does mean that the GGXF interface must support accessing the individual GGXF groups, which I think is a good idea in any case.  The interface will need to support a simplified access for the common case of just one group.  

Note 999:  Below is adapted from a snake_case attribute example - obvious adaptation to camelCase!  The notes above use somewhat mixed convention for attribute names depending on whether it is more a YAML or NetCDF context.  For simplicity I am leaning against my previous preference and thinking that it may be simpler to retain camelCase for non ACDD attributes.

```
netcdf deformation {

// global attributes:
    :Conventions = "GGXF-1.0, ACDD-1.3" ;
    ...
    :parameters.count = 3LL ;
    :parameters.1.parameter_name = "displacementEast" ;
    :parameters.1.length_unit = "metre" ;
    :parameters.1.unit_si_ratio = 1. ;
    :parameters.1.vector_name = "displacement";
    :parameters.1.crs_axis = 1;
    :parameters.2.parameter_name = "displacementNorth" ;
    :parameters.2.length_unit = "metre" ;
    :parameters.2.unit_si_ratio = 1. ;
    :parameters.2.vector_name = "displacement";
    :parameters.2.crs_axis = 0;
    :parameters.3.parameter_name = "displacementUp" ;
    :parameters.3.length_unit = "metre" ;
    :parameters.3.unit_si_ratio = 1. ;
    :parameters.3.vector_name = "displacement";
    :parameters.3.crs_axis = 2;
    :parameters.4.parameter_name = "displacementHorizontalUncertainty" ;
    :parameters.4.length_unit = "metre" ;
    :parameters.4.unit_si_ratio = 1. ;
    :parameters.4.vector_name = "displacementUncertainty";
    :parameters.5.parameter_name = "displacementVerticalUncertainty" ;
    :parameters.5.length_unit = "metre" ;
    :parameters.5.unit_si_ratio = 1. ;
    :parameters.5.vector_name = "displacementUncertainty";

group: nz_linz_vert_vel {
  dimensions:
    displacement_count = 1 ;
    displacementUncertainty_count = 1;

      :group_parameters = "displacementUp,displacementVerticalUncertainty" ;
      ...

  group: hvel {
    dimensions:
      i_node_count = 3 ;
      j_node_count = 4 ;
    variables:
      float displacement(j_node_count, i_node_count, displacement_count) ;
      float displacementUncertainty(j_node_count, i_node_count, displacementUncertainty_count) ;
    data:
     displacement = 0.44, ... ;
     displacementUncertainty = 0.12, ... ;
    }
  }

group: nz_linz_hypo_eq {
  dimensions:
    displacement_count = 3 ;
    displacementUncertainty_count = 2;
    
      string :group_parameters = "displacementEast", "displacementNorth", "displacementUp, displacementHorizontalUncertainty,displacementVerticalUncertainty" ;

  group: eqdef1 {
    dimensions:
      i_node_count = 5 ;
      j_node_count = 6 ;
    variables:
      float displacement(j_node_count, i_node_count, displacement_count) ;
      float displacementUncertainty(j_node_count, i_node_count, displacmentUncertaintyCount) ;
    ...
    data:
     displacement = 1.24, ... ;
     displacementUncertainty = 0.03, ... ;

    group: eqdef2 {
      dimensions:
        i_node_count = 5 ;
        j_node_count = 3 ;
      variables:
        float displacement(j_node_count, i_node_count, displacement_count) ;
        float displacementUncertainty(j_node_count, i_node_count, displacmentUncertaintyCount) ;
      ...
      data:
       displacement = 1.48, ... ;
       displacementUncertainty = 0.02, ... ;
      } 
    }
  }
}

```

**Comment by ccrook** [comment]
@desruisseaux In terms of comparison my main motivation in this alternative is in notes 0 and 1 above - I would like to be able to build a GGXF reader library that can read any GGXF file without domain knowledge, so I want the mapping of scalar parameter names to vector variable names to be explicit in the GGXF file, not depend on domain knowledge or some sort inference based on names. 

I acknowledge that this does make the determination of vector variable names and axes some complex as the groupParameters is used to compile the names of the NetCDF variables and CRS axes they refer to.  However I think it is straightforward and unambiguous.

The second aspect of this - crs axis attribute in parameter definition makes sense to me logically and adds no further complexity.

If I understand correctly your main motivations for restructuring the original NetCDF POC are:

* unambiguous mapping to CRS axes where applicable (not just a NetCDF concern when I think about it)
* more NetCDF conventional variables and potential efficiency from grouping parameters into different variables

I think this proposal addresses both of these points.  How does it look to you?

**Comment by desruisseaux** [comment]
Hello Chris

Thanks for this proposal, it looks fine to me. A concern would be that a header with attributes structured using a dot convention (e.g. `parameters.1.parameter_name`) feels like inventing a format inside the format, but a compound type like #38 may solve that. Below are relatively minor details:

> Could there be a case where it needs to refer to a targetCRS axis that is not also a sourceCRS axis.

Yes, I mentioned that possibility previously. I think it would be useful to specify not only the axis on which a parameter applies, but also on which CRS (source or target).

> Not sure of the best name for this attribute. Given concern about potential misinterpretation of "vector" perhaps something generic like "parameter_set" may be better?

Or `tuple_variable`? `storage_variable`? `data_variable`?

> The variables in each ggxfGridGroup and the order of parameters in them is defined by the `group_parameters` attribute in the ggxfGroup

This group attribute seems to define a reverse navigation from netCDF group to GGXF, by opposition with the header which defines a forward navigation from GGXF to netCDF variables. Is that right? If yes, do we need this attribute given that it could be inferred relatively easily from the header in Chris's proposal?

If we chose to keep this attribute, would it be more convenient to move it as netCDF variable attributes instead of a group attribute? It would be a little bit more accurate (we know the variables) at the cost of requiring a loop if implementer wants to list all GGXF parameters in a group (but conversely, filtering by variables become easier). Note: in my original proposal, `axis_parameters` was a group attribute because it was closely related to the `axis_indices` attribute, but this is no longer the case in Chris's proposal.

>  In the NetCDF implementation the dimension defining the number of parameters in a vector variable shall be defined by a dimension using the name of the variable with `_count` appended.

Would it be our own requirement or is it a requirement from CF or other conventions? In the former case, could we leave the choice of dimension names to data producers instead? The way I usually handle a netCDF file is to fetch the variable of interest, then fetch its dimensions. Then, usually what matter is the dimension order rather than their names. This approach applies to GGXF as well, where the dimension order are the order of input coordinates in the affine transform, and the "count" dimension is simply the last dimension after all grid coordinates. So the dimension names does not matter, only their declaration order in a variable matter.

> It may worth including the "crsAxis" and "vectorName" attributes in the GGXF and YAML specification

I'm neutral on `vectorName` (especially if it is renamed `storageName`, which looks more like implementation details), but at least `crsAxis` seems to me an important information for geodetic calculations, not only an implementation details. Even if it could be inferred from CRS WKT and parameter name, it is difficult enough (it requires WKT parsing and some "intelligence" for mapping parameter names to axis directions, yet more complicated in polar cases) for deserving being explicit.

**Comment by ccrook** [comment]
> > Could there be a case where it needs to refer to a targetCRS axis that is not also a sourceCRS axis.
> 
> Yes, I mentioned that possibility previously. I think it would be useful to specify not only the axis on which a parameter applies, but also on which CRS (source or target).

Can you give me an example?  If this is a mapping from a source CRS to a target CRS then I would have thought the axis would have to be in both of them?

**Comment by ccrook** [comment]
> The variables in each ggxfGridGroup and the order of parameters in them is defined by the group_parameters attribute in the ggxfGroup
> 
> This group attribute seems to define a reverse navigation from netCDF group to GGXF, by opposition with the header which defines a forward navigation from GGXF to netCDF variables. Is that right? If yes, do we need this attribute given that it could be inferred relatively easily from the header in Chris's proposal?
> 
> If we chose to keep this attribute, would it be more convenient to move it as netCDF variable attributes instead of a group attribute? 

I don't think so.  The groupParameters attribute defines which parameters apply within that group, which make be a subset of those that are available in the entire file.  This is the case in the deformation model examples.  The code can then use the parameter definitions to ascertain which variables will be defined in the group and the mapping of variable indices to CRS axes. 

It is a group level attribute, not a grid level attribute, so using group level avoids repetition.  But also making a variable attribute means looking at variables, checking if they have a group parameters, seeing of the variable name is consistent with the parameterSet of those parameters, etc.

**Comment by ccrook** [comment]
> > In the NetCDF implementation the dimension defining the number of parameters in a vector variable shall be defined by a dimension using the name of the variable with _count appended.
> 
> Would it be our own requirement or is it a requirement from CF or other conventions? In the former case, could we leave the choice of dimension names to data producers instead? 

I was proposing this as a convention for ggxf.  In fact it doesn't matter what it is called so long as it doesn't conflict with the other dimensions used in the group.  It isn't a concern of the data producer (if they are generating YAML), more of the GGXF translator or library.

> The way I usually handle a netCDF file is to fetch the variable of interest, then fetch its dimensions. 

Hopefully the way of dealing with a GGXF file will be to use GGXF library functions :-)

**Comment by ccrook** [comment]
> > It may worth including the "crsAxis" and "vectorName" attributes in the GGXF and YAML specification
> 
> I'm neutral on vectorName (especially if it is renamed storageName, which looks more like implementation details), but at least crsAxis seems to me an important information for geodetic calculations, not only an implementation details. 

I'm leaning to sourceCrsAxis and parameterSet as the attribute names.  (Subject to discussion above as to whether there is ever a requirement or desire to use targetCrsAxis instead or as well).

**Comment by ccrook** [comment]
This is now resolved.  The parameter definitions include optional attributes parameterSet, which defines the NetCDF variable name, and sourceCrsAxis which identifies numerically the axis of the sourceCrs to which a variable applies.
