### ISSUE TITLE
Should GGXF file include option for test points

### ISSUE THREAD

**Issue by RogerLott** [opengeospatial/CRS-Gridded-Geodetic-data-eXchange-Format#51]
Should the GGXF format include an option for providing test/check coordinates for those content types which support coordinate operations? For content = Cartesian2DOffsets a possible capability for might be:

checkPoint:
  sourceCrsCoords:
    easting:  1234.567
    northing: 3456.789
  targetCrsCoords:
    easting: 1234.89
    northing: 3456.987

The identity of the source and target CRSs and the units for the coordinates are assumed to be those from the CRS definitions in the file header. The names of the coordinates come from Topic 2 / ISO 19111.

Applying this general structure to content = geoidModel and a point with a geoid height of 44.404 (units, here metres):

checkPoint:
  sourceCrsCoords:
    geodeticLatitude: 57.456
    geodeticLongitude: 1.608
    ellipsoidalHeight: 44.404
  targetCrsCoords:
    gravity-relatedHeight: 0.00
  
where the hyphen in gravity-related comes from Topic 2 / ISO 19111.

The coordinates in general are numbers. But to cater for latitude and longitude in sexagesimal degrees we provide additional keywords: 

checkPoint:
  sourceCrsCoords:
    geodeticLatitudeString: 57°27'21.600"N
    geodeticLongitudeString: 1°36'28.800"E
    ellipsoidalHeight: 44.404
  targetCrsCoords:
    gravity-relatedHeight: 0.00
  

An example with time-dependent coordinates using content = velocityGrid is:

checkPoint:
  sourceCrsCoords:
    geodeticLatitude: 57.456
    geodeticLongitude: 1.608
    ellipsoidalHeight: 44.404
    coordinateEpoch: 2015.00
  targetCrsCoords:
    geodeticLatitude: 57.45600005
    geodeticLongitude: 1.60799996
    ellipsoidalHeight: 44.405
    coordinateEpoch: 2022.87

There is no restriction on the number of check points that may be included in the file.

In which header should check points be included - file, ggxfGroup or grid?

**Comment by ccrook** [comment]
Sounds a very good optional element to me. 

> There is no restriction on the number of check points that may be included in the file.

Definitely must support multiple test points - it would serve little purpose otherwise.  To achieve this in YAML would require

``` YAML
checkPoints:
  - sourceCrsCoords:
    targetCrsCoords:
  - sourceCrsCoords:
    targetCrsCoords
```

Note that this isn't just testing the content or reading of the GGXF file, it is also testing the application of that coordinate operation by the software using the GGXF.  Also the conversion of the source (or target) coordinate to the interpolations CRS.

I think it may be worth adding a parameterValues: to each entry to allow testing parameters such as uncertainties that are not directly used in coordinate operations, and to also identify whether the error comes from the grid interpolation or from the application of the resultant parameter values.

The problem child (deformation) would also need an epoch as an input for each check (checkEpoch: ?)

> In which header should check points be included - file, ggxfGroup or grid?

As the proposed test is testing the coordinate operation it applies to the whole dataset, so I think it belongs in the file header.  It is in a similar category to the discovery metadata, not directly required operationally but supporting the dataset.  The group and grid are I think just operational data - details of the dataset itself.

**Comment by RogerLott** [comment]
@ccrook 
> would also need an epoch as an input for each check (checkEpoch: ?)

Is this covered in my 4th (last) example, or something extra?

**Comment by RogerLott** [comment]
r3 includes check data option.
